### ISSUE TITLE
schedule.run_pending() hammering CPU

### ISSUE THREAD

**Issue by glennvdb** [viseshrp/fbn#1]
Hey, I've just start using your project. 
I've noticed that the script uses a lot of cpu, and this is due to:
```python
while True:
    schedule.run_pending()
```

Consider to add a time.sleep() in the while loop, like so:

```python
while True:
    time.sleep(1000)
    schedule.run_pending()
```

**Comment by glennvdb** [comment]
I get an error that I could not figure out. For some reason, when the software is trying to get the latest posts using fb.get_latest_posts, it gives an error in which it tries to request the page: https://m.facebook.com/settings, although, I never configured to request that page whatsoever. Any ideas?

**Comment by viseshrp** [comment]
@glennvdb Hey, yes. Sorry about that. I did not pay much attention to the CPU. Let me make that change and do a release.

**Comment by viseshrp** [comment]
Pushed a release. Might take a few minutes to show up. Let me know if that works out well. Thanks again! @glennvdb 
https://github.com/viseshrp/fbn/actions/runs/5405652333
