### ISSUE TITLE
Request to settings that I did not configure 

### ISSUE THREAD

**Issue by glennvdb** [viseshrp/fbn#2]
I get an error that I could not figure out. For some reason, when the software is trying to get the latest posts using fb.get_latest_posts, it gives an error in which it tries to request the page: https://m.facebook.com/settings, although, I never configured to request that page whatsoever. Any ideas? 

The error that appears is: ConnectionResetError: [Errno 54] Connection reset by peer

**Comment by viseshrp** [comment]
@glennvdb Hey there. Yes, so the facebook.com/settings page is pinged by the facebook-scraper lib to first check authentication. The error you are experiencing is because you are scraping too often. Try to reduce the frequency. If you don't provide a frequency in fbn, it will randomize from 2-4 hours which has been working well for me. Rotate your cookies from time to time and try without the `--every` option.

**Comment by viseshrp** [comment]
More info: https://github.com/kevinzg/facebook-scraper/issues/763

**Comment by glennvdb** [comment]
> @glennvdb Hey there. Yes, so the facebook.com/settings page is pinged by the facebook-scraper to first check authentication. The error you are experiencing is because you are scraping too often. Try to reduce the frequency. If you don't provide a frequency in fbn, it will randomize from 2-4 hours which has been working well for me. Rotate your cookies from time to time and try without the --frequency option.

Would it also suffice to pass authentication details only instead of generating multiple cookies? I really want to run this for a very long time in the background, and I don't like to have to rotate cookies every now and then.

**Comment by viseshrp** [comment]
@glennvdb yes, we can through facebook-scraper and I can add that option to fbn. Unfortunately, from experience, that increases your chances of being banned by Facebook's bot detection. That is why I never went that way in fbn.

**Comment by viseshrp** [comment]
@glennvdb Actually I just realized I have that option added in already. Check the README.
